### ISSUE TITLE
[discussion] Windows  Isolation

### ISSUE THREAD

**Issue by F-TD5X** [dwizzzle/Presentations#2]
> I am not sure if you are open to a discussion in the issue tracker, but since there are no other chat rooms available.

I wanted to address a topic from the presentation: 'Windows 11 Security by Default.'

Many of us are interested in the 'container' method for Win32 applications. However, a large portion of Win32 'normal' applications will try to install/load a driver to achieve a certain goal. Will this security method be transparent to such apps?

You mentioned that this security method relies on a small driver for support. However, some applications that require a driver to run (for security reasons, or if they force the user to allow it to load a driver, or some dirty way such as driver mapping) may not be compatible with this security feature. This is especially concerning because many Windows users may not possess enough knowledge or expertise to identify potentially harmful applications or use Windows safely. Although an admin-less approach may work in some cases, what can be done if the application "forces" an evaluation?

It appears that the packer method is similar to that used in tools such as VMware ThinApp or XenStudio/Turbo.net. I'm not sure if there will be other ways to create packs from isolated containers besides using Hyper-V. (yes I forgot what it used to be called.)

**Comment by sundhaug92** [comment]
Re that last bit: Windows supports userland containers
